### ISSUE TITLE
`%` stops working in visual mode for brackets

### ISSUE THREAD

**Issue by albertas** [airblade/vim-matchquote#11]
`%` operator stops working in visual mode for brackets `[({`, when this plugin is installed in NVIM v0.8.0-1210-gd367ed9b2.

In normal mode the `%` correctly matches pair bracket, but in visual mode it does nothing and cancels the visual mode instead of matching bracket.

**Comment by airblade** [comment]
I can't reproduce this with Neovim's [0.8.0 release](https://github.com/neovim/neovim/releases/tag/v0.8.0).

Please could you link or post your nvim config and list of plugins?

**Comment by airblade** [comment]
Closing because this has gone quiet.  Let me know if you're still having trouble.

**Comment by albertas** [comment]
I have installed newest LunarVim version with Neovim 0.8.0 and could no longer reproduce this behavior. Bracket matching is working just fine in visual mode. Thanks.

**Comment by airblade** [comment]
Thank you for reporting back and I'm glad it's working for you.
