### ISSUE TITLE
Add support for g:no_plugin_maps = 1

### ISSUE THREAD

**Issue by laktak** [airblade/vim-matchquote#13]
Thanks for your plugin! 

I've added support for `g:no_plugin_maps = 1` by using Plug instead of a `%` mapping.

I'm not opening a PR because I've replaced most of the fallback logic - but if you find it useful you can get it from:

https://github.com/laktak/vim-matchquote

**Comment by airblade** [comment]
Thanks for posting your work!

The fallback logic is frankly annoying and if I'd like to ditch it and adopt your approach.  But I feel I should try to maintain some backward compatibility.  Although I never decided how much...
