### ISSUE TITLE
Doesn't work in Visual mode

### ISSUE THREAD

**Issue by savchenko** [airblade/vim-matchquote#2]
Excellent idea, but seems to not work in visual mode. Test case, cursor is marked:
```
...years ago. |"Voila!"
              ^
```
Pressing <kbd>v</kbd> makes Vim select first quote, but subsequent <kbd>%</kbd> changes nothing.

In normal mode, plugin functions as intended. Tested in Vim v8.0 and NeoVim v0.3.4.

**Comment by airblade** [comment]
Yes, visual mode isn't supported yet.  I'll add it soon.

**Comment by airblade** [comment]
Visual mode added in 4f628dc.
