### ISSUE TITLE
Matching single quotes

### ISSUE THREAD

**Issue by savchenko** [airblade/vim-matchquote#5]
Seems like plugin doesn't match single quotes despite definition of "quotes" variable:https://github.com/airblade/vim-matchquote/blob/7546e5011deeb21cb538d29e072da1743cfe05c8/plugin/matchquote.vim#L32
Testing on the line #72:
https://github.com/airblade/vim-matchquote/blob/7546e5011deeb21cb538d29e072da1743cfe05c8/plugin/matchquote.vim#L72
With cursor on the first <kbd>'</kbd>, pressing % in normal mode does nothing.

**Comment by airblade** [comment]
Works for me.  What does `:nmap %` say?

**Comment by savchenko** [comment]
It says: `n  %           * :<C-U>call <SNR>59_Match_wrapper('',1,'n') <CR>`

Checked further, works in normal vim from Debian stable:
`Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)` 

Does not work in NeoVim v0.3.4 and v0.3.7 (latest version in "testing" Debian branch and latest one directly from @neovim).

Interestingly, it _does work_ in NeoVim if sourced manually and [matchquote](https://github.com/airblade/vim-matchquote) is the only plugin loaded:
```
>  nvim -N -u NONE -i NONE
:so ~/.vim/plugins/vim-matchquote/plugin/matchquote.vim
```

**Comment by airblade** [comment]
That's helpful, thanks.

It could be to do with the order plugins are loaded.  Vim and NeoVim have loaded the matchit plugin in various ways over time, and if it were loaded after vim-matchquote we'd see this behaviour.

The fix would be to deduce `s:matchit_n_rhs` and `s:matchit_x_rhs` lazily instead of eagerly.

I'll be able to get to this soon.

**Comment by airblade** [comment]
On further thought, my comment above doesn't quite explain the problem.  The mapping you saw shows that matchit has overwritten vim-matchquote, so matchit is being loaded after vim-matchquote – which isn't expected.

**Comment by savchenko** [comment]
Reading about matchit, it seems to be included in current vim distribution `:help matchit-install` and in the [vim repository](https://github.com/vim/vim/tree/master/runtime/pack/dist/opt/matchit), but not installed by default.

I suspect that nvim treats its loading differently as adding `let loaded_matchit = 1` to the `~/.vimrc` fixed the problem with single quotes.

Here is the mapping after the tweak above: `n  %             :call <SNR>18_matchquote('n')<CR>`

**Comment by airblade** [comment]
Does adding something like this (untested) fix it for you?

```viml
" /plugin/matchquote.vim
if has('nvim')
  let loaded_matchit = 1
endif
```

**Comment by savchenko** [comment]
Yes, moving `loaded_matchit = 1` into the conditional at the top of `matchquote.vim` fixes the issue.

**Comment by airblade** [comment]
Great, thanks for confirming that.
