### ISSUE TITLE
Error when calling matchquote in Visual mode

### ISSUE THREAD

**Issue by savchenko** [airblade/vim-matchquote#6]
nVim v0.3.4 (Debian stable)

Test, cursor is indicated with the caret sign:
```
fnames=(curl www http wget aria2c passwd password crypt sha1 md5 rc4 arcfour tls ftp ssl GET $rgx_ips)
       ^
```
Pressing sequentially: <kbd>v</kbd> and <kbd>%</kbd>

Error message:
```
Error detected while processing function <SNR>29_matchquote[4]..<SNR>29_fallback_to_original:
line   15:
E488: Trailing characters: :<C-U>call <SNR>13_Match_wrapper('',1,'v') <CR>m'gv``
```

**Comment by airblade** [comment]
If you set `let g:loaded_matchquote=1` in your `init.vim` and restart nvim, what does this produce: `:map %`?

Update: don't worry, I found it out:

```viml
vnoremap <silent> %  :<C-U>call <SID>Match_wrapper('',1,'v') <CR>m'gv``
```

https://github.com/neovim/neovim/blob/ab2bbbf6c45fdf278271d19f014c9d0850d249c6/runtime/plugin/matchit.vim#L56

**Comment by savchenko** [comment]
Is there anything else I can do? In normal mode, without visual selection, it works as expected - cursor jumps between `()`

**Comment by airblade** [comment]
From the comments I wrote in the code, I don't think I was expecting the stuff after the `<CR>` – it was a long time ago so I can't remember ;)

I'm sure it just needs a small tweak to get it going.

(I'm away at the moment though so it might be a day or two...)

**Comment by savchenko** [comment]
Thanks for looking into it! I have tried removing the jump after the `<cr>`, but to no avail:
```
Error detected while processing function <SNR>61_matchquote[4]..<SNR>61_fallback_to_original:
line   15:
E488: Trailing characters: :<C-U>call <SNR>13_Match_wrapper('',1,'v') <CR>
```
Will tinker with it, but given my experience with the vimscript (not much), it might take longer than patiently waiting for you to return :)

**Comment by airblade** [comment]
Here's a patch:

```diff
diff --git i/plugin/matchquote.vim w/plugin/matchquote.vim
index f77421f..aa56eef 100644
--- i/plugin/matchquote.vim
+++ w/plugin/matchquote.vim
@@ -23,6 +24,12 @@ if s:matchit_n_rhs =~# 'Match_wrapper'
   " Make the function easier to call ourselves.
   let s:matchit_n_rhs = s:matchit_n_rhs[6:]  " drop leading :<C-U>
   let s:matchit_n_rhs = substitute(s:matchit_n_rhs, '<CR>', '', '')  " drop trailing <CR>
+
+  let s:matchit_x_rhs = s:matchit_x_rhs[6:]  " drop leading :<C-U>
+  let s:matchit_x_rhs = substitute(s:matchit_x_rhs, '\s\?<CR>', '', '')  " drop trailing <CR>
+  if s:matchit_x_rhs[-1:] != ')'
+    let s:matchit_x_rhs = substitute(s:matchit_x_rhs, ')', ') | normal! ', '')
+  endif
 endif
 
 if s:matchit_n_rhs =~# '<Plug>'
```

I don't have neovim to hand to test this with, so I'll be amazed if it works :)

**Comment by savchenko** [comment]
Works as a treat!

**Comment by savchenko** [comment]
Works as a treat! Thank you for fixing it.

**Comment by airblade** [comment]
Thanks for confirming!
