### ISSUE TITLE
Unexpected behaviour in visual mode

### ISSUE THREAD

**Issue by mgarort** [airblade/vim-matchquote#8]
Hello again :)

I have found that the plugin doesn't work as I would expect in visual mode. Instead of always matching the quote under the cursor, it goes back to matching the quote where the selection started. For example, in the following example, where `^` marks the cursor position and `V` marks the visual selection:
```
"hello" 'goodbye'
^
V
```

pressing `%` in this example matches the desired quote, which results in:

```
"hello" 'goodbye'
      ^
VVVVVVV
```

this is the desired behaviour. However, if I try to match the single quotes `'`, and I press `%` starting from:

```
"hello" 'goodbye'
        ^
VVVVVVVVV
```

the resulting selection goes back to:

```
"hello" 'goodbye'
      ^
VVVVVVV
```

whereas in fact what I would expect is:

```
"hello" 'goodbye'
                ^
VVVVVVVVVVVVVVVVV
```

The latter would allow to compose the `%` matching operation in more complex selections that also use other `f`, `F`, `t` and `T` or other plugins such as vim-sneak.

Is this behaviour a bug in my system? Or am I trying to use vim-matchquote beyond its intended application?

Thanks!

**Comment by airblade** [comment]
Thanks for another clear and detailed report :)

There were two problems with the code:

- In visual mode when a mapping calls a function, vim switches to normal mode.  I had forgotten about that.  The code thought the cursor was at the end of the visual selection when in fact the selection had disappeared.
- I was unnecessarily setting the start of the visual selection (`'<`) which messed up more complex selections.

It's working properly now.
