### ISSUE TITLE
Percentage-wise movement with N% not working

### ISSUE THREAD

**Issue by mgarort** [airblade/vim-matchquote#9]
Hi,

First of all, thanks for the plugin! I find vim-matchquote very useful.

I have encountered the folllowing undesired behaviour: `%` is hijacked by vim-matchquote, regardless of whether
- the cursor is in a matchable character such as `(`, `[`, `{`, etc, or
- a count is provided before `%`.

Therefore, I cannot navigate to the line at the half of the file by doing `50%`. This is important because I work with large files often, and moving percentage wise is very quick and intuitive in these situations.

May I suggest that:

- vim-matchquote doesn't do anything if `%` is pressed when the cursor is not on a matchable character.
- If a count is given before `%`, for example with `50%`, vim-matchquote falls back to the default percentage-wise motion.

**Comment by airblade** [comment]
Hmm, it's supposed to fall back to the original behaviour when `%` is pressed when the cursor is not on a matchable character: [see here](https://github.com/airblade/vim-matchquote/blob/e2aa1ee987c5694b8f9427335e98bbbf57d43bf6/plugin/matchquote.vim#L52-L55).

Somehow I didn't know about `N%`.

I'll try to come up with a fix.

**Comment by mgarort** [comment]
Thanks for the super quick reply!

I see about the fallback behaviour. I guess I've only experienced it when I did `N%`.

About the fix, what about something like this?

`nnoremap <expr> % (v:count == 0 ? ':call <SNR>47_matchquote("n")<CR>' : '%')`

If you press just `%`, then `v:count` is 0, so it gets mapped to the relevant matchquote function. But if you press `50%`, then `v:count` is 50, so it gets mapped to the usual `50%`.

**Comment by airblade** [comment]
That looks like a good idea.  Does this work for you?

```diff
diff --git i/plugin/matchquote.vim w/plugin/matchquote.vim
index 4cc24e7..dd0d543 100644
--- i/plugin/matchquote.vim
+++ w/plugin/matchquote.vim
@@ -105,7 +105,7 @@ function! s:character_at_cursor()
 endfunction
 
 
-nnoremap <silent> %      :call <SID>matchquote('n')<CR>
+nnoremap <silent> <expr> % (v:count == 0 ? ":call <SID>matchquote('n')<CR>" : '%')
 xnoremap <silent> % :<C-U>call <SID>matchquote('x')<CR>
 
 if empty(maparg('i<Bar>', 'x')) && empty(maparg('a<Bar>', 'x'))
```

**Comment by mgarort** [comment]
Yes, I've tested it in `.vim/bundle/vim-matchquote/plugin/matchquote.vim` and it works :+1:

**Comment by airblade** [comment]
Thanks for letting me know about the problem, and for the solution!
